name: Build ZMK firmware
on:
  pull_request:
    paths-ignore:
      - "keymap-app/**"
      - "docs/**"
      - "**/*.md"

jobs:
  firmware:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
